### PR TITLE
Easy model usage

### PR DESCRIPTION
**Pull request by splitice**
Now we can do

```
$data = new Incident();
$data->blah = $blah;
$cachet->createIncident($data);
```

### CODE REVIEW

**Comment by splitice** [comment]
Ive appended a couple more small commits. Some missing fields from the Incidents model, and some PHPDoc that makes the experience in IDEs better.

**Comment by Jord-JD** [comment]
I really like the elegant syntax.

What do you think about adding a `create` method to base model that calls the relevant `$cachet->createFoo` method? This would mean we could do the following, which is very Laravel/Eloquent like.

```
$incident = new Incident();
$incident->blah = $blah;
$incident->create();
```

**Comment by splitice** [comment]
Reading my mind mate. Working towards it one pr at a time.

That then eliminates the static factories making it more easily unit testable.

**Comment by splitice** [comment]
Although I'd eliminate the createFoo altogether

**Comment by Jord-JD** [comment]
Yeah, I'd agree. Once we have all the objects calling the factory methods, we can get rid of the extra creation methods in `CachetInstance` object.

**Comment by Jord-JD** [comment]
Would you like to add more to this one or shall I merge it?

**Comment by splitice** [comment]
Whichever you prefer, this is just the small stuff I found while using it in the project I'm working on.

I'll do the above discussed stuff (unless you do it) over the weekend.

I also need to implement incident updates (3.0/master)

**Comment by Jord-JD** [comment]
Okay. I'll leave this one open for now.

Feel free to add other small bits to this one or create new PR(s) where appropriate.

**Comment by splitice** [comment]
Appended create & delete method abstraction

**Comment by splitice** [comment]
I also think metricpoint should just accept $row like everything else. Theres metric_id in the $row for referencing the metric.

**Comment by Jord-JD** [comment]
I'm going to get this merged into master now. If you want to continue work on it, feel free to open another pull requests.

I'll probably revisit these updates soon and start getting things together for a v0.3 release if appropriate.

Thanks for your work! :)

**Pull request merged**
