### PR TITLE
Cleanup & Abstraction Improvement

### PR DESCRIPTION
**Pull request by splitice**
- Better organized for future unit testing
- IntelliJ/PHPStorm IDE files & composer.phar ignored
- Can pass models in instead of arrays for transmission
- API communication abstracted out of multiple places and interfaced for any future changes
- API is also somewhat improved with the intent of making pagination upgrades easier in the future
- Multiple warnings fixed

### CODE REVIEW

**Comment by Jord-JD** [comment]
Some awesome work! Thanks. :smile: 

If you can apply the StyleCI patch, I'll get this merged.

**Comment by splitice** [comment]
You are welcome to modify as necessary.

**Comment by Jord-JD** [comment]
I've tied all this together in my recent commits to master. Thanks.

**Comment by splitice** [comment]
Ah didnt realize that I didnt push the last commit for CachetInstance. Oops.

Unit tests would have caught that. Probably should be on the list :)

**Comment by Jord-JD** [comment]
No problem. I definitely agree with adding in some unit testing, I'll add an issue for it.

**Pull request merged**
